version: 6.0.0-beta.2-{build}

image: Visual Studio 2015

# cache version - netcoreapp.2.0.0-preview1-002106-00
cache:
  - '%LocalAppData%\Microsoft\dotnet -> appveyor.yml'
  - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> appveyor.yml'

nuget:
  project_feed: true

install:
  - git submodule update --init
  - ps: Import-Module .\tools\Appveyor.psm1
  - ps: Invoke-AppveyorInstall

build_script:
  - ps: Invoke-AppveyorBuild

test_script:
  - ps: Invoke-AppveyorTest

after_test:
  - ps: Invoke-AppVeyorAfterTest

on_finish: 
  - ps: Invoke-AppveyorFinish
